name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Ubuntu Build
        run: cargo build --release --all-features
      - name: Upload Ubuntu Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Ubuntu Build
          path: target/release/main
          if-no-files-found: warn
      - name: Windows Build
        run: cargo build --release --all-features --target x86_64-pc-windows-msvc
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Linux Build
          path: target/release/main.exe
          if-no-files-found: warn
