name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-pc-windows-msvc, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add ${{ matrix.target }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features --target ${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Ubuntu Build
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
